_BASE_: "../Base-RetinaNet.yaml"
MODEL:
    WEIGHTS: "model_0229999.pth"
    RESNETS:
        DEPTH: 50
    BACKBONE:
        NAME: "build_retinanet_swint_fpn_backbone"
    SWINT:
        OUT_FEATURES: ["stage3", "stage4", "stage5"]
    FPN:
        IN_FEATURES: ["stage3", "stage4", "stage5"]
SOLVER:
    STEPS: (3000, 5000)
    MAX_ITER: 10000
    WEIGHT_DECAY: 0.05
    BASE_LR: 0.0001
    IMS_PER_BATCH: 3
    AMP:
        ENABLED: True
DATASETS:
    TRAIN: ("drawing",)
    TEST: ("drawing",)
